//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BirdsControl
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bird
    {
        public int Id { get; set; }
        public string Specie { get; set; }
        public string SubSpecie { get; set; }
        public Nullable<System.DateTime> HatchingDate { get; set; }
        public string Sex { get; set; }
        public string CageNumber { get; set; }
        public Nullable<int> DadID { get; set; }
        public Nullable<int> MomID { get; set; }
    }
}
